from data.static import EQUIP_TYPE_2, SHIP_TYPE
from battle.static import FORMATION, HOUGEKI_CUTIN

ASW_EQUIP_TYPE2 ={ EQUIP_TYPE_2.CARRIER_DIVE_BOMBER,
                   EQUIP_TYPE_2.CARRIER_TORPEDO_BOMBER,
                   EQUIP_TYPE_2.SEAPLANE_BOMBER,
                   EQUIP_TYPE_2.SONAR,
                   EQUIP_TYPE_2.DEPTH_CHARGE,
                   EQUIP_TYPE_2.AUTOGYRO,
                   EQUIP_TYPE_2.ANTI_SUBMARINE_PATROL,
                   EQUIP_TYPE_2.LARGE_SONAR}

DEPTH_CHARGE_ID = {226, 227, 378, 439, 488}
DEPTH_CHARGE_PROJECTOR_ID = {44, 45, 287, 288, 377, 472}
ASW_DC_DCP_SYNERGY = 1.1
ASW_DC_DCP_SONAR_SYNERGY = 1.25
ASW_LEGACY_SONAR_SYNERGY = 1.15

FORMATION_MODIFIER = {
    FORMATION.LINE_AHEAD: 1,
    FORMATION.DOUBLE_LINE: 0.8,
    FORMATION.DIAMOND: 0.7,
    FORMATION.ECHELON: 0.75,
    FORMATION.LINE_ABREAST: 0.6,
    FORMATION.CF1: 0.8,
    FORMATION.CF2: 1,
    FORMATION.CF3: 0.7,
    FORMATION.CF4: 1.1
}

FORMATION_MODIFIER_ECHELON_VS_CF = 0.6
FORMATION_MODIFIER_VANGUARD_UHALF = 0.6
FORMATION_MODIFIER_VANGUARD_LHALF = 1
FORMATION_MODIFIER_VANGUARD_UHALF_ASW = 1
FORMATION_MODIFIER_VANGUARD_LHALF_ASW = 0.5

FORMATION_MODIFIER_ASW = {
    FORMATION.LINE_AHEAD: 0.6,
    FORMATION.DOUBLE_LINE: 0.8,
    FORMATION.DIAMOND: 1.2,
    FORMATION.ECHELON: 1.1,
    FORMATION.LINE_ABREAST: 1.3,
    FORMATION.CF1: 1.3,
    FORMATION.CF2: 1.1,
    FORMATION.CF3: 1,
    FORMATION.CF4: 0.7
}

CL_SINGLE_GUN_ID = {4, 11}
CL_TWIN_GUN_ID = {65, 119, 139, 303, 310, 359, 360, 361, 407}
ZARA_CLASS_CTYPE = 64

FIGHTER_BOMBER_ID = {60, 154, 219, 447}

AP_SHELL_WEAK_SHIP_TYPES = {SHIP_TYPE.CA,
                            SHIP_TYPE.CAV,
                            SHIP_TYPE.FBB,
                            SHIP_TYPE.BB,
                            SHIP_TYPE.BBV,
                            SHIP_TYPE.CV,
                            SHIP_TYPE.CVB}

HOUGEKI_CUTIN_MODIFIER = {
    HOUGEKI_CUTIN.SINGLE_ATTACK: 1,
    HOUGEKI_CUTIN.DOUBLE_ATTACK: 1.2,
    HOUGEKI_CUTIN.MAIN_SECONDARY: 1.1,
    HOUGEKI_CUTIN.MAIN_RADAR: 1.2,
    HOUGEKI_CUTIN.MAIN_AP: 1.3,
    HOUGEKI_CUTIN.MAIN_MAIN: 1.5,
    HOUGEKI_CUTIN.ZUIUN_MULTI_ANGLE: 1.35,
    HOUGEKI_CUTIN.AIR_SEA_MULTI_ANGLE: 1.3,
}

class HOUGEKI_SPATTACK_MODIFIER:
    NELSON_TOUCH = 2
    NELSON_TOUCH_RED_T = 2.5

    NAGATO_BROADSIDE_BASE = 1.4
    NAGATO_BROADSIDE_PARTNER_BASE = 1.2

    COLORADO_SPECIAL_BASE = 1.5
    COLORADO_SPECIAL_PARTNER_BASE = 1.3

    YAMATO_3SHIP_BASE = 1.5
    YAMATO_3SHIP_THIRD_PARTNER_BASE = 1.65

    YAMATO_2SHIP_BASE = 1.4
    YAMATO_2SHIP_PARTNER_BASE = 1.55

