"""Battle constants
"""

from dataclasses import dataclass
from typing import Union
from battle.ship import Ship
from api_parsing.static import HougekiAttack, KoukuAttack, MidnightAttack, RaigekiAttack

class BATTLE_TYPE:
    NORMAL = "api_req_sortie/battle"
    NIGHT = "api_req_battle_midnight/battle"
    NIGHT_START = "api_req_battle_midnight/sp_midnight"
    AERIAL_EXCHANGE = "api_req_sortie/airbattle"
    AERIAL_RAID = "api_req_sortie/ld_airbattle"
    RADAR_AMBUSH = "api_req_sortie/ld_shooting"

    SINGLE_VS_COMBINED = "api_req_combined_battle/ec_battle"
    SINGLE_VS_COMBINED_NIGHT = "api_req_combined_battle/ec_midnight_battle"
    SINGLE_VS_COMBINED_NIGHT_TO_DAY = "api_req_combined_battle/ec_night_to_day"

    COMBINED_NIGHT = "api_req_combined_battle/midnight_battle"
    COMBINED_NIGHT_START = "api_req_combined_battle/sp_midnight"
    AERIAL_EXCHANGE_COMBINED = "api_req_combined_battle/airbattle"
    AERIAL_RAID_COMBINED = "api_req_combined_battle/ld_airbattle"
    RADAR_AMBUSH_COMBINED = "api_req_combined_battle/ld_shooting"

    CTF_TCF_VS_SINGLE = "api_req_combined_battle/battle"
    CTF_TCF_VS_COMBINED = "api_req_combined_battle/each_battle"

    STF_VS_SINGLE = "api_req_combined_battle/battle_water"
    STF_VS_COMBINED = "api_req_combined_battle/each_battle_water"


class PHASE:
    # Day
    LAND_BASE_JET = "api_air_base_injection"
    JET = "api_injection_kouku"
    LAND_BASE = "api_air_base_attack"
    FRIENDLY_AIRBATTLE = "api_friendly_kouku"
    AIRBATTLE = "api_kouku"
    AIRBATTLE2 = "api_kouku2"
    SUPPORT = "api_support_info"
    OPENING_ASW = "api_opening_taisen"
    OPENING_TORPEDO = "api_opening_atack"
    SHELLING = "api_hougeki1"
    SHELLING2 = "api_hougeki2"
    SHELLING3 = "api_hougeki3"
    CLOSING_TORPEDO = "api_raigeki"

    # Night
    FRIENDLY_SHELLING = "api_friendly_battle"
    NIGHT_SUPPORT = "api_n_support_info"
    NIGHT_SHELLING = "api_hougeki"
    NIGHT_SHELLING1 = "api_n_hougeki1"
    NIGHT_SHELLING2 = "api_n_hougeki2"


class BATTLE_ORDER:
    NORMAL = [PHASE.LAND_BASE_JET, PHASE.JET, PHASE.LAND_BASE, PHASE.FRIENDLY_AIRBATTLE, PHASE.AIRBATTLE,
              PHASE.AIRBATTLE2, PHASE.SUPPORT, PHASE.OPENING_ASW, PHASE.OPENING_TORPEDO, PHASE.SHELLING,
              PHASE.SHELLING2, PHASE.SHELLING3, PHASE.CLOSING_TORPEDO]

    NIGHT = [PHASE.FRIENDLY_SHELLING,
             PHASE.NIGHT_SUPPORT, PHASE.NIGHT_SHELLING]

    SINGLE_VS_COMBINED = [PHASE.LAND_BASE_JET, PHASE.JET, PHASE.LAND_BASE, PHASE.FRIENDLY_AIRBATTLE, PHASE.AIRBATTLE,
                          PHASE.AIRBATTLE2, PHASE.SUPPORT, PHASE.OPENING_ASW, PHASE.OPENING_TORPEDO, PHASE.SHELLING,
                          PHASE.CLOSING_TORPEDO, PHASE.SHELLING2, PHASE.SHELLING3]

    NIGHT_TO_DAY = [PHASE.FRIENDLY_SHELLING, PHASE.NIGHT_SUPPORT, PHASE.NIGHT_SHELLING1, PHASE.NIGHT_SHELLING2,
                    PHASE.LAND_BASE_JET, PHASE.JET, PHASE.LAND_BASE, PHASE.FRIENDLY_AIRBATTLE, PHASE.AIRBATTLE,
                    PHASE.SUPPORT, PHASE.OPENING_ASW, PHASE.OPENING_TORPEDO, PHASE.SHELLING, PHASE.SHELLING2, PHASE.CLOSING_TORPEDO]

    CTF_TCF_VS_COMBINED = [PHASE.LAND_BASE_JET, PHASE.JET, PHASE.LAND_BASE, PHASE.FRIENDLY_AIRBATTLE, PHASE.AIRBATTLE,
                           PHASE.AIRBATTLE2, PHASE.SUPPORT, PHASE.OPENING_ASW, PHASE.OPENING_TORPEDO, PHASE.SHELLING,
                           PHASE.SHELLING2, PHASE.CLOSING_TORPEDO, PHASE.SHELLING3]

    def get(x: str):
        return BATTLE_TYPE_ORDER_MAPPING[x]


BATTLE_TYPE_ORDER_MAPPING = {
    BATTLE_TYPE.NORMAL: BATTLE_ORDER.NORMAL,
    BATTLE_TYPE.NIGHT: BATTLE_ORDER.NIGHT,
    BATTLE_TYPE.NIGHT_START: BATTLE_ORDER.NIGHT,
    BATTLE_TYPE.AERIAL_EXCHANGE: BATTLE_ORDER.NORMAL,
    BATTLE_TYPE.AERIAL_RAID: BATTLE_ORDER.NORMAL,
    BATTLE_TYPE.RADAR_AMBUSH: BATTLE_ORDER.NORMAL,

    BATTLE_TYPE.SINGLE_VS_COMBINED: BATTLE_ORDER.SINGLE_VS_COMBINED,
    BATTLE_TYPE.SINGLE_VS_COMBINED_NIGHT: BATTLE_ORDER.NIGHT,
    BATTLE_TYPE.SINGLE_VS_COMBINED_NIGHT_TO_DAY: BATTLE_ORDER.NIGHT_TO_DAY,

    BATTLE_TYPE.COMBINED_NIGHT: BATTLE_ORDER.NIGHT,
    BATTLE_TYPE.COMBINED_NIGHT_START: BATTLE_ORDER.NIGHT,
    BATTLE_TYPE.AERIAL_EXCHANGE_COMBINED: BATTLE_ORDER.NORMAL,
    BATTLE_TYPE.AERIAL_RAID_COMBINED: BATTLE_ORDER.NORMAL,
    BATTLE_TYPE.RADAR_AMBUSH_COMBINED: BATTLE_ORDER.NORMAL,

    BATTLE_TYPE.CTF_TCF_VS_SINGLE: BATTLE_ORDER.SINGLE_VS_COMBINED,
    BATTLE_TYPE.CTF_TCF_VS_COMBINED: BATTLE_ORDER.CTF_TCF_VS_COMBINED,

    BATTLE_TYPE.STF_VS_SINGLE: BATTLE_ORDER.NORMAL,
    BATTLE_TYPE.STF_VS_COMBINED: BATTLE_ORDER.NORMAL
}


class ENGAGEMENT:
    PARALLEL = 1
    HEAD_ON = 2
    GREEN_T = 3
    RED_T = 4


class FORMATION:
    LINE_AHEAD = 1
    DOUBLE_LINE = 2
    DIAMOND = 3
    ECHELON = 4
    LINE_ABREAST = 5
    VANGUARD = 6
    CF1 = 11
    CF2 = 12
    CF3 = 13
    CF4 = 14


class HITSTATUS:
    MISS = 0
    HIT = 1
    CRITICAL = 2


class HOUGEKI_CUTIN:
    SINGLE_ATTACK = 0
    LASER = 1
    DOUBLE_ATTACK = 2
    MAIN_SECONDARY = 3
    MAIN_RADAR = 4
    MAIN_AP = 5
    MAIN_MAIN = 6
    CARRIER_CUTIN = 7
    NELSON_TOUCH = 100
    NAGATO_SPECIAL = 101
    MUTSU_SPECIAL = 102
    COLORADO_SPECIAL = 103
    ZUIUN_MULTI_ANGLE = 200
    AIR_SEA_MULTI_ANGLE = 201
    SUBFLEET_SPECIAL_1 = 300
    SUBFLEET_SPECIAL_2 = 301
    SUBFLEET_SPECIAL_3 = 302
    YAMATO_3SHIP_CUTIN = 400
    YAMATO_2SHIP_CUTIN = 401


class YASEN_CUTIN:
    SINGLE_ATTACK = 0
    DOUBLE_ATTACK = 1
    MAIN_TORP_CUTIN = 2
    TORP_TORP_CUTIN = 3
    MAIN_MAIN_SEC_CUTIN = 4
    MAIN_MAIN_MAIN_CUTIN = 5
    CARRIER_CUTIN = 6
    DD_MAIN_TORP_RADAR = 7
    DD_TORP_LOOKOUT_RADAR = 8
    DD_TORP_LOOKOUT_TORP = 9
    DD_TORP_LOOKOUT_DRUM = 10
    DD_MAIN_TORP_RADAR2 = 11
    DD_TORP_LOOKOUT_RADAR2 = 12
    DD_TORP_LOOKOUT_TORP2 = 13
    DD_TORP_LOOKOUT_DRUM2 = 14
    NELSON_TOUCH = 100
    NAGATO_SPECIAL = 101
    MUTSU_SPECIAL = 102
    COLORADO_SPECIAL = 103
    KONGOU_K2_CUTIN = 104
    NIGHT_ZUIUN_CUTIN = 200
    SUBFLEET_SPECIAL_1 = 300
    SUBFLEET_SPECIAL_2 = 301
    SUBFLEET_SPECIAL_3 = 302
    YAMATO_3SHIP_CUTIN = 400
    YAMATO_2SHIP_CUTIN = 401


class SPECIAL_ATTACK_ATTACKERS:
    NELSON_TOUCH = [0, 2, 4]
    NAGATO_MUTSU_SPECIAL = [0, 0, 1]
    COLORADO_SPECIAL = [0, 1, 2]
    KONGOU_K2_CUTIN = [0, 1]
    YAMATO_3SHIP_CUTIN = [0, 1, 2]
    YAMATO_2SHIP_CUTIN = [0, 0, 1]


SPECIAL_ATTACKS = [
    HOUGEKI_CUTIN.NELSON_TOUCH,
    HOUGEKI_CUTIN.NAGATO_SPECIAL,
    HOUGEKI_CUTIN.MUTSU_SPECIAL,
    HOUGEKI_CUTIN.COLORADO_SPECIAL,
    YASEN_CUTIN.KONGOU_K2_CUTIN,
    HOUGEKI_CUTIN.SUBFLEET_SPECIAL_1,
    HOUGEKI_CUTIN.SUBFLEET_SPECIAL_2,
    HOUGEKI_CUTIN.SUBFLEET_SPECIAL_3,
    HOUGEKI_CUTIN.YAMATO_3SHIP_CUTIN,
    HOUGEKI_CUTIN.YAMATO_3SHIP_CUTIN
]


SPECIAL_ATTACK_ATTACKER_MAPPING = {
    HOUGEKI_CUTIN.NELSON_TOUCH: SPECIAL_ATTACK_ATTACKERS.NELSON_TOUCH,
    HOUGEKI_CUTIN.NAGATO_SPECIAL: SPECIAL_ATTACK_ATTACKERS.NAGATO_MUTSU_SPECIAL,
    HOUGEKI_CUTIN.MUTSU_SPECIAL: SPECIAL_ATTACK_ATTACKERS.NAGATO_MUTSU_SPECIAL,
    YASEN_CUTIN.KONGOU_K2_CUTIN: SPECIAL_ATTACK_ATTACKERS.KONGOU_K2_CUTIN,
    HOUGEKI_CUTIN.YAMATO_3SHIP_CUTIN: SPECIAL_ATTACK_ATTACKERS.YAMATO_3SHIP_CUTIN,
    HOUGEKI_CUTIN.YAMATO_2SHIP_CUTIN: SPECIAL_ATTACK_ATTACKERS.YAMATO_2SHIP_CUTIN
}

@dataclass
class BattleAttack:
    attacker: Ship
    defender: Ship
    attacker_hp: int
    defender_hp: int
    attack: Union[HougekiAttack, RaigekiAttack, KoukuAttack, MidnightAttack]
